### ISSUE TITLE
object has no attribute 'classifier'

### ISSUE THREAD

**Issue by okmmsky888** [clintval/gender_predictor#2]
@clintval  I run gp.classify ('Aldo') and reported the following error:
File "G:\faceAging\genderPrediction\gender_predictor-master\gender_predictor\__init__.py", line 40, in classify
    return(self.classifier.classify(self._name_features(name.upper())))
AttributeError: 'GenderPredictor' object has no attribute 'classifier'

What is the cause of this？

**Comment by clintval** [comment]
Hi @okmmsky888, you need to create a classifier internally first. Notice the line before where we call `train_and_test()` which builds the classifier:

```python
>> from gender_predictor import GenderPredictor
>> gp = GenderPredictor()
'import complete'
'32,031 male names'
'56,347 female names'

>> gp.train_and_test()
'classifier accuracy: 96.74%'

>> gp.classify('Aldo')
'M'
```
The classifier that is built into the library is the [`nltk.NaiveBayesClassifier`](https://github.com/clintval/gender_predictor/blob/master/gender_predictor/__init__.py#L48) and the features that are being used for each name can be found in the private method [`GenderPredictor._name_features()`](https://github.com/clintval/gender_predictor/blob/master/gender_predictor/__init__.py#L52-L57). You can, of course, override these methods if you subclass `GenderPredictor`.

I'll consider adding a better exception message than the generic `AttributeError` that you encountered to help other first time users.

**Comment by clintval** [comment]
By the way, if you have your own testing set you may want to confirm that this classifier will work well for your corpus of names. If not, you will have to train on a subset of your names and see if you get better accuracy.

**Comment by okmmsky888** [comment]
@clintval    Okay thank you. I only used the first time, run gp.train_and_test ()

**Comment by clintval** [comment]
Exactly, do that once after instantiating the class and then you're good to go.
